# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\info1\Desktop\qt_designer\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEditPrenom = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPrenom.setGeometry(QtCore.QRect(10, 40, 281, 20))
        self.lineEditPrenom.setObjectName("lineEditPrenom")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 47, 13))
        self.label.setObjectName("label")
        self.lineEdit_Nom = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Nom.setGeometry(QtCore.QRect(10, 110, 281, 20))
        self.lineEdit_Nom.setText("")
        self.lineEdit_Nom.setObjectName("lineEdit_Nom")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 160, 47, 13))
        self.label_3.setObjectName("label_3")
        self.lineEdit_ID = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ID.setGeometry(QtCore.QRect(10, 180, 281, 20))
        self.lineEdit_ID.setText("")
        self.lineEdit_ID.setObjectName("lineEdit_ID")
        self.checkBoxVIP = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxVIP.setGeometry(QtCore.QRect(10, 230, 70, 17))
        self.checkBoxVIP.setObjectName("checkBoxVIP")
        self.checkBoxDanger = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxDanger.setGeometry(QtCore.QRect(10, 250, 121, 31))
        self.checkBoxDanger.setObjectName("checkBoxDanger")
        self.pushButtonAdd = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAdd.setGeometry(QtCore.QRect(50, 320, 191, 31))
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(343, 20, 431, 521))
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Prenom"))
        self.label_2.setText(_translate("MainWindow", "Nom"))
        self.label_3.setText(_translate("MainWindow", "ID"))
        self.checkBoxVIP.setText(_translate("MainWindow", "V.I.P"))
        self.checkBoxDanger.setText(_translate("MainWindow", "Danger for society"))
        self.pushButtonAdd.setText(_translate("MainWindow", "Add"))
